/** Auto-generated from process manual CSV — do not edit by hand. */

export type HRScenarioRole = 'org-admin' | 'manager' | 'employee' | 'partner-admin';

export interface HRScenarioRow {
  entryId: string;
  guide: string;
  ref: string;
  title: string;
  purpose: string;
  outcome: string;
  stepsText: string;
  formData: string;
  testData: string;
  notes: string;
  role: HRScenarioRole;
  route: string;
  skipPreLogin: boolean;
  setupKey: null | 'org-admin-tickets' | 'employee-tickets' | 'partner-admin-tickets';
}

export const HR_SCENARIO_ROWS: HRScenarioRow[] = [
  {
    entryId: 'org-admin--1-1',
    guide: 'Organisation Admin',
    ref: '1.1',
    title: 'Logging In',
    purpose: 'Authenticate as an organisation admin and open the admin dashboard.',
    outcome: 'Signed in; land on Admin Dashboard.',
    stepsText: 'Open http://localhost:3001/?org=platform-demo | Enter Email address | Enter Password | Click Sign in',
    formData: 'Email (e.g. helen.richardson@platform-demo.com); Password (e.g. Demo123!)',
    testData: 'EXISTING: URL ?org=platform-demo | Email helen.richardson@platform-demo.com | Password Demo123!',
    notes: 'Replace URL for production. Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: true,
    setupKey: null,
  },
  {
    entryId: 'org-admin--1-2',
    guide: 'Organisation Admin',
    ref: '1.2',
    title: 'Understanding the Navigation',
    purpose: 'Reach all admin modules from the sidebar.',
    outcome: 'User knows menu items: Dashboard, Users, Directory, Org Chart, Calendar, Tasks, Reports, Performance, Announcements, Tickets, Knowledge Centre, Partnerships, Settings, Health & Safety, Activity Log.',
    stepsText: 'Use left sidebar to open each area as needed',
    formData: 'N/A',
    testData: 'EXISTING: No input — seeded menus include Dashboard, Users, Directory, Org Chart, Calendar, Tasks, Reports, Performance, Announcements, Tickets, Knowledge Centre, Partnerships, Settings, Health & Safety, Activity Log.',
    notes: 'Informational. Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--1-3',
    guide: 'Organisation Admin',
    ref: '1.3',
    title: 'Switching Admin / Employee View',
    purpose: 'Preview the product as an employee without losing admin access.',
    outcome: 'View toggles between Admin and Employee.',
    stepsText: 'Top bar: locate Admin / Employee toggle | Click Employee or Admin',
    formData: 'N/A',
    testData: 'EXISTING: No input — use Admin/Employee toggle only.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--2-1',
    guide: 'Organisation Admin',
    ref: '2.1',
    title: 'Dashboard Components',
    purpose: 'See org-wide activity and risks at a glance.',
    outcome: 'Read activity feed, movements, task summary, celebrations, training gaps, quick links.',
    stepsText: 'After login remain on Dashboard | Scroll to review widgets',
    formData: 'N/A',
    testData: 'EXISTING: No input — dashboard widgets populated from demo org (e.g. movements, tasks, celebrations).',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--2-2',
    guide: 'Organisation Admin',
    ref: '2.2',
    title: 'Using Quick Actions',
    purpose: 'Jump to common work from the dashboard.',
    outcome: 'New user flow, task list, or employee profile opens.',
    stepsText: 'Click Add new user OR View all tasks OR click a celebration card',
    formData: 'N/A until destination screen',
    testData: 'EXISTING: Quick actions — Add new user opens create flow; View all tasks → Tasks; celebration cards may include e.g. Jonathan Hartley (MD).',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--3-1',
    guide: 'Organisation Admin',
    ref: '3.1',
    title: 'Viewing the User List',
    purpose: 'Find and open employee records.',
    outcome: 'Filtered or searched list of employees.',
    stepsText: 'Sidebar: Users | Use search bar | Apply filters: department, division, status, access level | Click employee name',
    formData: 'Search text; filter selections',
    testData: 'EXISTING: Users → search Taylor → Ben Taylor (Logistics Coordinator, Operations) OR search helen → Helen Richardson.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--3-2',
    guide: 'Organisation Admin',
    ref: '3.2',
    title: 'Creating a New User',
    purpose: 'Add an employee record and optionally invite them.',
    outcome: 'User created; system may prompt to send invitation email.',
    stepsText: 'Users | Add User | Complete fields | Save | Follow invitation prompt if shown',
    formData: 'Required: First name; Last name; Email address (work); Country (e.g. United Kingdom); Access level (Organisation Admin, Manager, or UK Employee). Optional: Department; Division; Job title; Employee number; Date of birth; Gender; Marital status; Phone numbers; Address',
    testData: 'NEW: First name ManualTest | Last name RecordHire | Email manualtest.hire.UNIQUE@example.com (replace UNIQUE; must not match any user in Users) | Country United Kingdom | Access UK Employee | Optional: Department Operations | Job Title QA Recording | Employee Number MT-UNIQUE | Save then invite if prompted.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--3-3',
    guide: 'Organisation Admin',
    ref: '3.3',
    title: 'Editing a User Profile',
    purpose: 'Maintain accurate HR, pay, leave, and compliance data.',
    outcome: 'Profile saved for that employee.',
    stepsText: 'Users | Click employee | Tabs: Personal, Employment, Pay, Leave, Documents, Emergency contacts, Notes, Training, Health & Safety | Edit on a section | Save',
    formData: 'Tab-specific fields as shown in UI',
    testData: 'EXISTING: Users → Ben Taylor (ben.taylor@platform-demo.com) → Personal tab → Edit → change Mobile to +44 7700 899001 (example) → Save.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--3-4',
    guide: 'Organisation Admin',
    ref: '3.4',
    title: 'Inviting a User',
    purpose: 'Send password-setup email.',
    outcome: 'Invitation email with secure link sent.',
    stepsText: 'Users | Open user profile | Click Send Invitation (when shown)',
    formData: 'Uses profile email; no separate form in guide',
    testData: 'EXISTING: Open the NEW user from 3.2 if invite available OR any user showing Send Invitation | Send Invitation.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--3-5',
    guide: 'Organisation Admin',
    ref: '3.5',
    title: 'Suspending or Removing a User',
    purpose: 'Block access or start leaver process.',
    outcome: 'Suspended and/or offboarding started with checklist.',
    stepsText: 'Open user profile | Suspend and/or Offboard | When prompted: enter leaving date and termination reason',
    formData: 'Leaving date; termination reason (offboarding)',
    testData: 'NEW (destructive): Only on disposable user: create ManualTest Leaver with unique email via 3.2 then Offboard | Leaving date +30 days from today | Reason End of fixed-term contract (test). Do not offboard real demo employees.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--4-1',
    guide: 'Organisation Admin',
    ref: '4.1',
    title: 'Using the Directory',
    purpose: 'Look up colleagues and open profiles.',
    outcome: 'Profile view for selected person.',
    stepsText: 'Directory | Browse or search | Click person',
    formData: 'Search/browse only',
    testData: 'EXISTING: Directory → search Johansson → Sarah Johansson (Operations Manager) OR browse Operations.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--4-2',
    guide: 'Organisation Admin',
    ref: '4.2',
    title: 'Viewing the Org Chart',
    purpose: 'See reporting lines visually.',
    outcome: 'Expanded/collapsed hierarchy.',
    stepsText: 'Org Chart (or Directory > Org Chart) | Click nodes to expand/collapse | Use zoom controls',
    formData: 'N/A',
    testData: 'EXISTING: Org Chart → expand Jonathan Hartley (Managing Director) to see hierarchy.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--5-1',
    guide: 'Organisation Admin',
    ref: '5.1',
    title: 'Company Calendar',
    purpose: 'See leave, holidays, and milestones org-wide.',
    outcome: 'Calendar with entry details on demand.',
    stepsText: 'Calendar | Month/week toggle | Filter by department, team, or individual | Click entry for details',
    formData: 'Filter selections',
    testData: 'EXISTING: Calendar → filter Human Resources | Click leave for Priya Sharma (pending block 21–24 Apr 2026 in seed) if shown.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--6-1',
    guide: 'Organisation Admin',
    ref: '6.1',
    title: 'Viewing Tasks',
    purpose: 'Monitor work across the organisation.',
    outcome: 'Filtered task list.',
    stepsText: 'Tasks | Filter by status (Open, In Progress, Completed), priority, category, assignee',
    formData: 'Filter selections',
    testData: 'EXISTING: Tasks → filter Category Onboarding or Assignee Sophie Turner (seeded tasks present).',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--6-2',
    guide: 'Organisation Admin',
    ref: '6.2',
    title: 'Creating a New Task',
    purpose: 'Assign tracked work with ownership and deadline.',
    outcome: 'New task in list; optional onboarding user link.',
    stepsText: 'Tasks | Create Task | Fill form | Optionally link onboarding user | Save',
    formData: 'Title; Category: Onboarding, Compliance, Training, or Administrative; Priority: Low, Medium, High, Urgent; Due date; Assignees (one or more); optional onboarding user link',
    testData: 'NEW: Title [ManualTest] Recording workflow task | Category Administrative | Priority Medium | Due date +14 days | Assignees Ben Taylor | Save.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--6-3',
    guide: 'Organisation Admin',
    ref: '6.3',
    title: 'Updating Task Status',
    purpose: 'Reflect progress and communicate.',
    outcome: 'Updated status and comments.',
    stepsText: 'Open task | Status dropdown: Open, In Progress, Completed | Add comments',
    formData: 'Status; comment text',
    testData: 'EXISTING: Open any task with status Open → set In Progress → add comment Recording test update.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--7-1',
    guide: 'Organisation Admin',
    ref: '7.1',
    title: 'Viewing Leave Requests',
    purpose: 'See who is off and per-person history.',
    outcome: 'Calendar overview and/or user Leave tab.',
    stepsText: 'Calendar and/or Users | user | Leave tab',
    formData: 'N/A',
    testData: 'EXISTING: Calendar overview OR Users → Priya Sharma → Leave tab (balances + history).',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--7-2',
    guide: 'Organisation Admin',
    ref: '7.2',
    title: 'Approving or Rejecting Leave',
    purpose: 'Apply policy to time off.',
    outcome: 'Request approved or rejected; employee notified.',
    stepsText: 'Open Pending request | Review dates, type, duration | Approve OR Reject | If Reject: provide reason',
    formData: 'Rejection reason when rejecting',
    testData: 'EXISTING: Open PENDING annual leave for Priya Sharma 2026-04-21–2026-04-24 (seed) → Approve OR Reject with reason Recording test rejection.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--7-3',
    guide: 'Organisation Admin',
    ref: '7.3',
    title: 'Configuring Leave Policies',
    purpose: 'Define accrual, carryover, approval.',
    outcome: 'Policies and workflows updated.',
    stepsText: 'Settings > Time & Leave | Manage Holidays, Leave policies, Approval workflows | Per policy: accrual type/frequency/days, carryover, caps, Bradford Factor (sick)',
    formData: 'Policy-specific fields per screen',
    testData: 'EXISTING: Settings → Time & Leave — reference seeded policies (Annual Leave, Sick Leave, etc.); adjust only in sandbox.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--7-4',
    guide: 'Organisation Admin',
    ref: '7.4',
    title: 'Managing Working Patterns',
    purpose: 'Align leave calculations with working weeks.',
    outcome: 'Patterns defined and assignable.',
    stepsText: 'Settings > Time & Leave | Define patterns | Assign to employees',
    formData: 'Pattern definition; employee assignment (per UI)',
    testData: 'EXISTING: Settings → Time & Leave — working patterns from seed; assign only in sandbox.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--8-1',
    guide: 'Organisation Admin',
    ref: '8.1',
    title: 'Performance Overview',
    purpose: 'See cycles, templates, 360 status.',
    outcome: 'Overview of active work.',
    stepsText: 'Performance | Review Active review cycles, Review templates, 360 feedback requests',
    formData: 'N/A',
    testData: 'EXISTING: Performance — active cycles/templates from seed (e.g. review instances for demo employees).',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--8-2',
    guide: 'Organisation Admin',
    ref: '8.2',
    title: 'Managing Review Cycles',
    purpose: 'Drill into cycle progress.',
    outcome: 'Opened review instance.',
    stepsText: 'Performance | Select cycle | View instances and completion % | Open a review',
    formData: 'N/A unless editing inside review',
    testData: 'EXISTING: Open cycle e.g. H1 2026 Performance Review if listed → drill into any in-progress instance.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--8-3',
    guide: 'Organisation Admin',
    ref: '8.3',
    title: 'Creating a New Review Cycle',
    purpose: 'Launch review period for applicable pairs.',
    outcome: 'New cycle with instances.',
    stepsText: 'Performance | Create Cycle | Select template | Cycle name, start date, end date | Launch',
    formData: 'Template; cycle name; start date; end date',
    testData: 'NEW: Create Cycle | Name [ManualTest] Recording cycle UNIQUE | Pick existing template | Start/End dates (future window) | Launch — use sandbox if cycles are restricted.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--8-4',
    guide: 'Organisation Admin',
    ref: '8.4',
    title: 'Managing Review Templates',
    purpose: 'Shape review forms.',
    outcome: 'Template saved with question types.',
    stepsText: 'Performance | Templates | Create/edit | Sections/questions: Text, Scale 1-5, Multiple choice, Two-axis graph',
    formData: 'Template name; section/question content and types',
    testData: 'EXISTING: Performance → Templates — edit copy of existing template or create draft (sandbox).',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--8-5',
    guide: 'Organisation Admin',
    ref: '8.5',
    title: '360 Feedback',
    purpose: 'Monitor peer feedback collection.',
    outcome: 'Visibility of reviewers and completion.',
    stepsText: 'Performance | 360 Feedback Requests | Inspect subject, reviewers, template',
    formData: 'N/A for monitoring',
    testData: 'EXISTING: Performance → 360 Feedback Requests — list from seed.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--9-1',
    guide: 'Organisation Admin',
    ref: '9.1',
    title: 'Viewing Announcements',
    purpose: 'Review communications.',
    outcome: 'List including pinned items.',
    stepsText: 'Announcements | View published, draft, scheduled',
    formData: 'N/A',
    testData: 'EXISTING: Announcements — seeded published/draft items visible.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--9-2',
    guide: 'Organisation Admin',
    ref: '9.2',
    title: 'Creating an Announcement',
    purpose: 'Broadcast to audience.',
    outcome: 'Published or draft announcement.',
    stepsText: 'Announcements | Create Announcement | Publish or save draft',
    formData: 'Title; Body (rich text); Priority (normal or high); Audience (all or filtered by team/division/country); Pin toggle',
    testData: 'NEW: Title [ManualTest] Scheduled maintenance notice | Body Short plain notice for recording | Priority normal | Audience All employees | Pin No | Publish or Draft.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--9-3',
    guide: 'Organisation Admin',
    ref: '9.3',
    title: 'Editing or Removing Announcements',
    purpose: 'Keep communications current.',
    outcome: 'Updated, unpublished, or deleted.',
    stepsText: 'Open announcement | Edit | Unpublish or delete as needed',
    formData: 'Same as create where applicable',
    testData: 'EXISTING: Open announcement you created in 9.2 → edit body → save; or unpublish test draft.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--10-1',
    guide: 'Organisation Admin',
    ref: '10.1',
    title: 'Ticket Inbox Overview',
    purpose: 'Triage employee support.',
    outcome: 'Filtered ticket queue.',
    stepsText: 'Tickets | Filter by status, category, assignee',
    formData: 'Filters only',
    testData: 'EXISTING: Tickets → filter Category IT Support | Row Unable to access VPN from home (Emma Fletcher) if enrich seed run.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: 'org-admin-tickets',
  },
  {
    entryId: 'org-admin--10-2',
    guide: 'Organisation Admin',
    ref: '10.2',
    title: 'Responding to a Ticket',
    purpose: 'Progress or resolve employee issues.',
    outcome: 'Thread updated; assignment/priority/status/escalation may change.',
    stepsText: 'Open ticket | Read thread | Type reply | Send | Optionally Assign, Change status, Change priority, Escalate to partner admin',
    formData: 'Reply text; status/priority/assignee; escalation if applicable',
    testData: 'EXISTING: Open ticket Unable to access VPN from home OR first open ticket | Reply Thanks — recording test | Send | optional status In Progress.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: 'org-admin-tickets',
  },
  {
    entryId: 'org-admin--10-3',
    guide: 'Organisation Admin',
    ref: '10.3',
    title: 'Managing Ticket Categories',
    purpose: 'Control categories for raised tickets.',
    outcome: 'Updated category list.',
    stepsText: 'Settings > Integrations & Data | Ticket Categories | Add, edit, remove',
    formData: 'Category fields per UI',
    testData: 'NEW (sandbox preferred): Settings → Integrations & Data → Ticket Categories → Add [ManualTest] Recording category UNIQUE — or edit label of disposable category.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: 'org-admin-tickets',
  },
  {
    entryId: 'org-admin--10-4',
    guide: 'Organisation Admin',
    ref: '10.4',
    title: 'Creating Ticket (Admin Inbox) — UI verified',
    purpose: 'Create ticket from org admin tickets area.',
    outcome: 'New ticket created.',
    stepsText: 'Tickets | Open New Ticket modal | Fill fields | Create Ticket',
    formData: 'Subject (required); Category (optional None); Priority (Low, Medium, High, Urgent); Description (required). Buttons: Cancel; Create Ticket / Creating…',
    testData: 'NEW: Tickets → New Ticket | Subject [ManualTest] Admin recording ticket | Category IT Support or None | Priority Low | Description Smoke test body | Create Ticket.',
    notes: 'Verified apps/admin-web tickets page. Modal title New Ticket.',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: 'org-admin-tickets',
  },
  {
    entryId: 'org-admin--11-1',
    guide: 'Organisation Admin',
    ref: '11.1',
    title: 'Managing Articles',
    purpose: 'Curate knowledge base.',
    outcome: 'View published and draft by category.',
    stepsText: 'Knowledge Centre | Browse by category',
    formData: 'N/A',
    testData: 'EXISTING: Knowledge Centre — articles by category from seed-demo-enrich (e.g. IT Help, HR Policies).',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--11-2',
    guide: 'Organisation Admin',
    ref: '11.2',
    title: 'Creating a New Article',
    purpose: 'Publish self-service guidance.',
    outcome: 'Article saved Published or Draft.',
    stepsText: 'Knowledge Centre | Create Article | Save',
    formData: 'Title; Category; Content (rich text); Published or Draft',
    testData: 'NEW: Create Article | Title [ManualTest] MFA reset steps | Category IT Help | Content Short bullet list | Draft | Save.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--11-3',
    guide: 'Organisation Admin',
    ref: '11.3',
    title: 'Editing and Organising Articles',
    purpose: 'Keep articles accurate.',
    outcome: 'Updated article.',
    stepsText: 'Open article | Edit content, category, status | Save per UI',
    formData: 'Per edit form',
    testData: 'EXISTING: Open any article → add (Recording) suffix to title → Save; or edit11.2 draft.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--12-1',
    guide: 'Organisation Admin',
    ref: '12.1',
    title: 'Reports Hub',
    purpose: 'Access reporting entry points.',
    outcome: 'Saved, favourites, ad-hoc areas visible.',
    stepsText: 'Reports | Saved reports / Favourites / Ad-hoc reports',
    formData: 'N/A',
    testData: 'EXISTING: Reports — saved/favourites/ad-hoc areas as seeded.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--12-2',
    guide: 'Organisation Admin',
    ref: '12.2',
    title: 'Available Report Types (reference)',
    purpose: 'Know built-in analytics routes.',
    outcome: 'User navigates to correct report.',
    stepsText: 'Main Reports /reports | Headcount /headcount | Additions & Terminations /additions-terminations | Turnover /turnover | Bradford Factor /bradford-factor',
    formData: 'N/A',
    testData: 'EXISTING: Paths /reports /headcount /additions-terminations /turnover /bradford-factor — navigate read-only.',
    notes: 'Paths from 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--12-3',
    guide: 'Organisation Admin',
    ref: '12.3',
    title: 'Running a Report',
    purpose: 'Produce dataset for period and cohort.',
    outcome: 'On-screen results; optional export.',
    stepsText: 'Open report | Set date range and filters | Export where available',
    formData: 'Date range; department, division, country, etc.; export format',
    testData: 'EXISTING: Run report with Date range 2026-01-01 to 2026-12-31 | Department Human Resources | Export if available.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--12-4',
    guide: 'Organisation Admin',
    ref: '12.4',
    title: 'Headcount Report',
    purpose: 'Analyse headcount trends.',
    outcome: 'Chart/table; export.',
    stepsText: 'Reports | Headcount | Breakdowns | Export',
    formData: 'Breakdown dimensions; export options',
    testData: 'EXISTING: Headcount | Monthly chart | Breakdown Department Human Resources.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--12-5',
    guide: 'Organisation Admin',
    ref: '12.5',
    title: 'Bradford Factor',
    purpose: 'Monitor short-term sickness patterns.',
    outcome: 'Filtered Bradford table.',
    stepsText: 'Bradford Factor | Filter by policy and period',
    formData: 'Policy type; date period',
    testData: 'EXISTING: Bradford Factor | filter period covering seeded sickness data.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--13-1',
    guide: 'Organisation Admin',
    ref: '13.1',
    title: 'Accessing Settings',
    purpose: 'Open configuration hub.',
    outcome: 'Settings category grid.',
    stepsText: 'Settings',
    formData: 'N/A',
    testData: 'EXISTING: Settings grid — no data entry required to open.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--13-2',
    guide: 'Organisation Admin',
    ref: '13.2',
    title: 'Settings Categories (reference)',
    purpose: 'Map configuration areas.',
    outcome: 'N/A informational.',
    stepsText: 'Read guide table: Organisation; People & Access; Pay & Benefits; Time & Leave; Hiring & Lifecycle; Learning & Development; Health & Safety; Integrations & Data; Account & Billing',
    formData: 'N/A',
    testData: 'EXISTING: Reference table only — Organisation, People & Access, etc.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--13-3',
    guide: 'Organisation Admin',
    ref: '13.3',
    title: 'Configuring Departments',
    purpose: 'Maintain department list.',
    outcome: 'Departments added/renamed/deactivated.',
    stepsText: 'Settings > Organisation > Departments | Add Department or open existing | Rename or deactivate',
    formData: 'Department name; active flag if applicable',
    testData: 'NEW (sandbox): Organisation → Departments → Add Department [ManualTest] Dept UNIQUE — or rename disposable dept only.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--13-4',
    guide: 'Organisation Admin',
    ref: '13.4',
    title: 'Managing Access Levels',
    purpose: 'Control capabilities per level.',
    outcome: 'Updated permission matrix.',
    stepsText: 'Settings > People & Access > Access Levels | Configure Organisation Admin, Manager, UK Employee',
    formData: 'Per-level permission toggles per UI',
    testData: 'EXISTING: People & Access → Access Levels — review Organisation Admin / Manager / UK Employee (read-only unless sandbox).',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--13-5',
    guide: 'Organisation Admin',
    ref: '13.5',
    title: 'Configuring Onboarding Task Lists',
    purpose: 'Define default new-starter tasks.',
    outcome: 'Checklist items for new hires.',
    stepsText: 'Settings > Hiring & Lifecycle > Onboarding | Add/reorder items',
    formData: 'Per item: Title; Description; Lead time (days before/after start); Priority; Assignee role',
    testData: 'EXISTING: Hiring & Lifecycle → Onboarding — checklist items from seed (titles, lead times). Add disposable item in sandbox only.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--13-6',
    guide: 'Organisation Admin',
    ref: '13.6',
    title: 'Configuring Offboarding Task Lists',
    purpose: 'Standardise leaver activities.',
    outcome: 'Tasks when offboarding starts.',
    stepsText: 'Settings > Hiring & Lifecycle > Offboarding | Define checklist items',
    formData: 'Per item per UI',
    testData: 'EXISTING: Hiring & Lifecycle → Offboarding — seeded lists; edit only in sandbox.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--13-7',
    guide: 'Organisation Admin',
    ref: '13.7',
    title: 'General Settings',
    purpose: 'Org-wide display and defaults.',
    outcome: 'Locale and self-service behaviour updated.',
    stepsText: 'Settings > Account & Billing > General Settings | Save',
    formData: 'Date format; Number format; Timezone; Default country; Display name format; Industry; Employee self-service options (photo upload, file upload, expanded gender options)',
    testData: 'EXISTING: Account & Billing → General Settings — verify date format/timezone; change only in sandbox (org-wide impact).',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--13-8',
    guide: 'Organisation Admin',
    ref: '13.8',
    title: 'Roles (Organisational Roles)',
    purpose: 'Group people for routing and visibility.',
    outcome: 'Role memberships updated.',
    stepsText: 'Settings > People & Access > Roles | Assign employees',
    formData: 'Role selections; employee assignments',
    testData: 'EXISTING: People & Access → Roles → e.g. HR Team — assign Sophie Turner if not already (verify in UI).',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--14-1',
    guide: 'Organisation Admin',
    ref: '14.1',
    title: 'Activity Log',
    purpose: 'Audit trail for compliance.',
    outcome: 'Filtered audit trail.',
    stepsText: 'Activity Log | Filter by date, user, action type',
    formData: 'Filter criteria',
    testData: 'EXISTING: Activity Log | Filter user Helen Richardson | Date last 7 days.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--14-2',
    guide: 'Organisation Admin',
    ref: '14.2',
    title: 'Access History',
    purpose: 'Review access-level changes.',
    outcome: 'Historical log.',
    stepsText: 'Access History (Audit & Logs area)',
    formData: 'Filters if present',
    testData: 'EXISTING: Access History — browse recent entries from seed activity.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'org-admin--14-3',
    guide: 'Organisation Admin',
    ref: '14.3',
    title: 'Import History',
    purpose: 'Verify bulk loads.',
    outcome: 'Past import results.',
    stepsText: 'Import History (Audit & Logs area)',
    formData: 'N/A',
    testData: 'EXISTING: Import History — empty or past runs per env.',
    notes: 'Source: 01-organisation-admin-guide.md',
    role: 'org-admin',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--1-1',
    guide: 'Manager',
    ref: '1.1',
    title: 'Logging In',
    purpose: 'Open manager (employee) shell.',
    outcome: 'Employee Dashboard at /me/dashboard.',
    stepsText: 'http://localhost:3001/?org=platform-demo | Email | Password | Sign in',
    formData: 'e.g. david.kowalski@platform-demo.com; Demo123!',
    testData: 'EXISTING: ?org=platform-demo | david.kowalski@platform-demo.com | Demo123!',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: true,
    setupKey: null,
  },
  {
    entryId: 'manager--1-2',
    guide: 'Manager',
    ref: '1.2',
    title: 'Manager Navigation',
    purpose: 'Use allowed menu items.',
    outcome: 'Correct area opens.',
    stepsText: 'Sidebar: Dashboard, My Profile, Directory, Org Chart, Calendar, Tasks, Performance, Raise a Ticket, Knowledge Centre, Partnerships, Settings',
    formData: 'N/A',
    testData: 'EXISTING: Sidebar — Dashboard, My Profile, Directory, Org Chart, Calendar, Tasks, Performance, Raise a Ticket, Knowledge Centre, Partnerships, Settings.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--1-3',
    guide: 'Manager',
    ref: '1.3',
    title: 'Key Difference from Employees',
    purpose: 'Set expectations for manager capabilities.',
    outcome: 'N/A informational.',
    stepsText: 'Read guide note on team profiles, leave approval, performance, team calendar',
    formData: 'N/A',
    testData: 'EXISTING: Informational — manager sees team approvals and /me/team routes.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--2-1',
    guide: 'Manager',
    ref: '2.1',
    title: 'Dashboard Overview',
    purpose: 'Personal and team snapshot.',
    outcome: 'Events, team activity, pending approvals, celebrations, quick actions.',
    stepsText: 'Land on Dashboard /me/dashboard',
    formData: 'N/A',
    testData: 'EXISTING: /me/dashboard — pending items may include Nathan Williams leave May 2026.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--2-2',
    guide: 'Manager',
    ref: '2.2',
    title: 'Acting on Dashboard Items',
    purpose: 'Act on notifications.',
    outcome: 'Leave flow, profile, or task opens.',
    stepsText: 'Click pending leave | team member name | task notification',
    formData: 'N/A until destination',
    testData: 'EXISTING: Click pending leave for Nathan Williams OR Emma Fletcher profile OR task link.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--3-1',
    guide: 'Manager',
    ref: '3.1',
    title: 'Viewing Team Members',
    purpose: 'Find direct reports.',
    outcome: 'Profile opened.',
    stepsText: 'Directory | Find reports (guide examples: Emma Fletcher, Nathan Williams, Aisha Patel) | Click member',
    formData: 'N/A',
    testData: 'EXISTING: Directory → Emma Fletcher (Account Executive) | Nathan Williams | Aisha Patel — direct reports of David Kowalski.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--3-2',
    guide: 'Manager',
    ref: '3.2',
    title: 'Viewing Team Member Profile',
    purpose: 'Read HR context for reports.',
    outcome: 'Personal, employment, leave, performance per permissions.',
    stepsText: 'Directory or /me/team/[userId]',
    formData: 'N/A',
    testData: 'EXISTING: Open /me/team/[userId] for Emma Fletcher or from Directory.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--3-3',
    guide: 'Manager',
    ref: '3.3',
    title: 'Org Chart',
    purpose: 'See hierarchy.',
    outcome: 'Expanded tree.',
    stepsText: 'Org Chart | Find self | Expand nodes',
    formData: 'N/A',
    testData: 'EXISTING: Org Chart — locate David Kowalski → expand to see sales team.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--4-1',
    guide: 'Manager',
    ref: '4.1',
    title: 'Viewing Pending Leave',
    purpose: 'Find requests needing approval.',
    outcome: 'Request identified.',
    stepsText: 'Dashboard and/or Calendar',
    formData: 'N/A',
    testData: 'EXISTING: Dashboard pending OR Calendar — Nathan Williams PENDING 18–20 May 2026 (seed).',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--4-2',
    guide: 'Manager',
    ref: '4.2',
    title: 'Approving Leave',
    purpose: 'Grant time off.',
    outcome: 'Employee notified; approved.',
    stepsText: 'Open pending request | Review name, leave type, dates, balance | Approve',
    formData: 'N/A',
    testData: 'EXISTING: Approve Nathan Williams annual leave 18–20 May 2026 (if still pending).',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--4-3',
    guide: 'Manager',
    ref: '4.3',
    title: 'Rejecting Leave',
    purpose: 'Decline with context.',
    outcome: 'Employee notified with reason.',
    stepsText: 'Open request | Reject | Provide reason',
    formData: 'Reason (required per guide)',
    testData: 'EXISTING: Reject a disposable test request OR use second pending with reason Coverage conflict (recording test).',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--4-4',
    guide: 'Manager',
    ref: '4.4',
    title: 'Team Calendar',
    purpose: 'Avoid clashes.',
    outcome: 'Team leave and UK bank holidays visible.',
    stepsText: 'Calendar',
    formData: 'N/A',
    testData: 'EXISTING: Calendar — team leave + UK bank holidays from seed.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--5-1',
    guide: 'Manager',
    ref: '5.1',
    title: 'Accessing Performance Reviews',
    purpose: 'Open reviews and 360.',
    outcome: 'Lists visible.',
    stepsText: 'Performance',
    formData: 'N/A',
    testData: 'EXISTING: Performance — own review + team reviews for Emma/Nathan/Aisha if cycles active.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--5-2',
    guide: 'Manager',
    ref: '5.2',
    title: 'Completing Review for Direct Report',
    purpose: 'Submit manager assessment.',
    outcome: 'Manager section submitted; sign if required after both submit.',
    stepsText: 'Open team review | Answer Text, Scale 1-5, Multiple choice | Submit | Sign if required',
    formData: 'All required answers; optional scale comments',
    testData: 'EXISTING: Open manager review for Emma Fletcher — fill required questions — Submit.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--5-3',
    guide: 'Manager',
    ref: '5.3',
    title: 'Completed Review Report',
    purpose: 'Read final record.',
    outcome: 'Report view with both sides.',
    stepsText: 'Open completed review | Report view',
    formData: 'N/A',
    testData: 'EXISTING: Completed review Report view if any completed instance exists.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--5-4',
    guide: 'Manager',
    ref: '5.4',
    title: '360 Feedback',
    purpose: 'Submit peer feedback.',
    outcome: 'Request complete.',
    stepsText: 'Open 360 request | Answer | Submit',
    formData: 'Template questions',
    testData: 'EXISTING: 360 request — complete if listed.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--6-1',
    guide: 'Manager',
    ref: '6.1',
    title: 'Viewing Tasks',
    purpose: 'See owned and delegated work.',
    outcome: 'Filtered list.',
    stepsText: 'Tasks | Filter status, priority, category',
    formData: 'Filters',
    testData: 'EXISTING: Tasks — filter tasks assigned to David Kowalski.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--6-2',
    guide: 'Manager',
    ref: '6.2',
    title: 'Updating a Task',
    purpose: 'Progress work.',
    outcome: 'Status and comments updated.',
    stepsText: 'Open task | Status Open, In Progress, Completed | Comments',
    formData: 'Status; comments',
    testData: 'EXISTING: Open task → In Progress → comment Recording test.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--6-3',
    guide: 'Manager',
    ref: '6.3',
    title: 'Creating a Task',
    purpose: 'Delegate work.',
    outcome: 'New task.',
    stepsText: 'Create Task | Fill title, category, priority, due date, assignees | Save',
    formData: 'Same categories as org admin task creation',
    testData: 'NEW: Create Task | Title [ManualTest] Manager delegation | Category Administrative | Priority Low | Due +7 days | Assignee Emma Fletcher | Save.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--7-1',
    guide: 'Manager',
    ref: '7.1',
    title: 'Raising a Ticket',
    purpose: 'Get HR/admin help.',
    outcome: 'Ticket created.',
    stepsText: 'Raise a Ticket (sidebar) | Click Raise a Ticket button (opens modal Raise a Ticket) | Fill | Create',
    formData: 'Subject (required); Category (optional None); Priority Low/Medium/High/Urgent; Route to Team (optional Select a team…); Description (required). Buttons: Cancel; Create / Creating…',
    testData: 'NEW: Raise a Ticket | Subject [ManualTest] Manager recording | Category General | Priority Medium | Route to Team HR Team (if listed) | Description Need policy clarification for recording | Create.',
    notes: 'UI verified me/tickets/page.tsx. Guide says New Ticket/Submit — app uses Raise a Ticket and Create.',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--7-2',
    guide: 'Manager',
    ref: '7.2',
    title: 'Ticket Conversations',
    purpose: 'Continue thread.',
    outcome: 'Updated conversation.',
    stepsText: 'Raise a Ticket | Open ticket | Read | Reply | Send',
    formData: 'Reply text',
    testData: 'EXISTING: Raise a Ticket → open your test ticket from 7.1 → reply Thanks resolved for recording | Send.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--7-3',
    guide: 'Manager',
    ref: '7.3',
    title: 'Knowledge Centre',
    purpose: 'Self-service reading.',
    outcome: 'Article opened.',
    stepsText: 'Knowledge Centre | Browse/search',
    formData: 'Search query',
    testData: 'EXISTING: Knowledge Centre — search policy or browse IT Help articles from enrich.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--7-4',
    guide: 'Manager',
    ref: '7.4',
    title: 'My Profile',
    purpose: 'Review/update allowed fields.',
    outcome: 'Profile updated if editable.',
    stepsText: 'My Profile | Edit allowed | Save',
    formData: 'Editable fields only',
    testData: 'EXISTING: My Profile — David Kowalski — view balances; edit allowed self-service fields only.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--7-5',
    guide: 'Manager',
    ref: '7.5',
    title: 'Account Settings',
    purpose: 'Personal preferences.',
    outcome: 'Settings saved.',
    stepsText: 'Settings (bottom of sidebar)',
    formData: 'Profile fields; birthday visibility; notifications',
    testData: 'EXISTING: Settings — birthday visibility / notifications — toggle and save if permitted.',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'manager--7-6',
    guide: 'Manager',
    ref: '7.6',
    title: 'Partnerships',
    purpose: 'View partner catalogue.',
    outcome: 'Informational browse.',
    stepsText: 'Partnerships',
    formData: 'N/A',
    testData: 'EXISTING: Partnerships — browse catalog (read-only).',
    notes: 'Source: 02-manager-guide.md',
    role: 'manager',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--1-1',
    guide: 'Employee',
    ref: '1.1',
    title: 'Accepting Invitation',
    purpose: 'Activate account.',
    outcome: 'Password set; redirect to platform.',
    stepsText: 'Email | Set Password link | Create password | Confirm',
    formData: 'Password meeting minimum rules shown in UI',
    testData: 'EXISTING: Invitation flow — use disposable invite only; email from invite | Set password per policy | Confirm.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--1-2',
    guide: 'Employee',
    ref: '1.2',
    title: 'Logging In',
    purpose: 'Access self-service.',
    outcome: 'Employee Dashboard.',
    stepsText: 'URL ?org=platform-demo | Email | Password | Sign in',
    formData: 'e.g. ben.taylor@platform-demo.com; Demo123!',
    testData: 'EXISTING: ben.taylor@platform-demo.com | Demo123! | ?org=platform-demo',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: true,
    setupKey: null,
  },
  {
    entryId: 'employee--1-3',
    guide: 'Employee',
    ref: '1.3',
    title: 'Reset Password',
    purpose: 'Regain access.',
    outcome: 'New password set.',
    stepsText: 'Forgot password? | Email | Reset link | New password',
    formData: 'Email; new password',
    testData: 'EXISTING: Forgot password? | ben.taylor@platform-demo.com | use reset email (test mailbox).',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--2-1',
    guide: 'Employee',
    ref: '2.1',
    title: 'Dashboard Overview',
    purpose: 'Home snapshot.',
    outcome: 'Events, actions, celebrations, announcements, links.',
    stepsText: '/me/dashboard',
    formData: 'N/A',
    testData: 'EXISTING: /me/dashboard — Ben Taylor events, tasks, announcements.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--2-2',
    guide: 'Employee',
    ref: '2.2',
    title: 'Acting on Dashboard',
    purpose: 'Deep-link to work.',
    outcome: 'Target screen opens.',
    stepsText: 'Click task | announcement | celebration | upcoming leave',
    formData: 'N/A',
    testData: 'EXISTING: Click task, announcement, celebration, or leave tile as shown.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--3-1',
    guide: 'Employee',
    ref: '3.1',
    title: 'Viewing Profile',
    purpose: 'See HR record.',
    outcome: 'Read personal, contact, employment, emergency, leave, training.',
    stepsText: 'My Profile',
    formData: 'N/A',
    testData: 'EXISTING: My Profile — Ben Taylor DEMO0019 Operations Logistics Coordinator reports Sarah Johansson.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--3-2',
    guide: 'Employee',
    ref: '3.2',
    title: 'Updating Profile',
    purpose: 'Keep contact data current.',
    outcome: 'Saved changes.',
    stepsText: 'My Profile | Edit section | Save',
    formData: 'Editable fields; job/salary admin-only per guide',
    testData: 'EXISTING: Edit allowed field e.g. Mobile +44 7700 888888 → Save (if self-service enabled).',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--3-3',
    guide: 'Employee',
    ref: '3.3',
    title: 'Photo Upload',
    purpose: 'Personalise directory.',
    outcome: 'Avatar updated.',
    stepsText: 'My Profile | Avatar | Select file',
    formData: 'Image file if enabled',
    testData: 'EXISTING: Avatar upload — small PNG if enabled by org.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--4-1',
    guide: 'Employee',
    ref: '4.1',
    title: 'Leave Balance',
    purpose: 'Know entitlement.',
    outcome: 'Balances visible.',
    stepsText: 'My Profile | Leave section',
    formData: 'N/A',
    testData: 'EXISTING: My Profile → Leave — Annual Leave balance from seed policies.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--4-2',
    guide: 'Employee',
    ref: '4.2',
    title: 'Submitting Leave',
    purpose: 'Request time off.',
    outcome: 'Pending request to manager.',
    stepsText: 'Dashboard or Calendar | Request Leave or Book Time Off | Leave type | Start/end dates | Optional note | Submit',
    formData: 'Leave type; dates; note',
    testData: 'NEW: Request Leave | Type Annual Leave | Start/End pick next available2 working days not conflicting seeded leave | Note Recording test request | Submit.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--4-3',
    guide: 'Employee',
    ref: '4.3',
    title: 'Leave Request Status',
    purpose: 'Track approval.',
    outcome: 'Colour-coded calendar and profile history.',
    stepsText: 'Calendar (green approved; yellow/orange pending; red rejected per guide) OR Profile Leave tab',
    formData: 'N/A',
    testData: 'EXISTING: Calendar — green/yellow/red for own requests | Profile Leave tab.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--4-4',
    guide: 'Employee',
    ref: '4.4',
    title: 'Cancelling Leave',
    purpose: 'Withdraw request.',
    outcome: 'Manager/system notified.',
    stepsText: 'Open request | Cancel Request if shown',
    formData: 'N/A',
    testData: 'EXISTING: Cancel only if UI allows on your own pending request from 4.2.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--5-1',
    guide: 'Employee',
    ref: '5.1',
    title: 'Calendar Overview',
    purpose: 'Plan around team and holidays.',
    outcome: 'Month/week view.',
    stepsText: 'Calendar | Month/week toggle',
    formData: 'N/A',
    testData: 'EXISTING: Calendar month/week — own + team leave + holidays.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--5-2',
    guide: 'Employee',
    ref: '5.2',
    title: 'Navigating Calendar',
    purpose: 'Move in time / inspect days.',
    outcome: 'Detail view.',
    stepsText: 'Arrows | Click date | Click leave entry',
    formData: 'N/A',
    testData: 'EXISTING: Navigate arrows | click date with leave.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--6-1',
    guide: 'Employee',
    ref: '6.1',
    title: 'Directory',
    purpose: 'Find colleagues.',
    outcome: 'Basic profile.',
    stepsText: 'Directory | Search | Click person',
    formData: 'Search',
    testData: 'EXISTING: Directory — search Richardson → Helen Richardson.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--6-2',
    guide: 'Employee',
    ref: '6.2',
    title: 'Org Chart',
    purpose: 'See structure.',
    outcome: 'Expanded view.',
    stepsText: 'Org Chart | Find self | Expand nodes',
    formData: 'N/A',
    testData: 'EXISTING: Org Chart — find Ben Taylor under Operations.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--7-1',
    guide: 'Employee',
    ref: '7.1',
    title: 'Tasks',
    purpose: 'See assignments.',
    outcome: 'Task list.',
    stepsText: 'Tasks',
    formData: 'N/A',
    testData: 'EXISTING: Tasks — tasks assigned to Ben Taylor from onboarding/compliance seed.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--7-2',
    guide: 'Employee',
    ref: '7.2',
    title: 'Updating Task',
    purpose: 'Report progress.',
    outcome: 'Updated task.',
    stepsText: 'Open task | Status | Comment',
    formData: 'Status; comment',
    testData: 'EXISTING: Open task → Completed or In Progress + comment.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--7-3',
    guide: 'Employee',
    ref: '7.3',
    title: 'Task Categories (reference)',
    purpose: 'Understand task types.',
    outcome: 'N/A informational.',
    stepsText: 'Read Onboarding, Compliance, Training, Administrative table in guide',
    formData: 'N/A',
    testData: 'EXISTING: Reference categories Onboarding, Compliance, Training, Administrative — seeded examples.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--8-1',
    guide: 'Employee',
    ref: '8.1',
    title: 'Performance Access',
    purpose: 'Open reviews/360.',
    outcome: 'Lists shown.',
    stepsText: 'Performance',
    formData: 'N/A',
    testData: 'EXISTING: Performance — self-assessment instance if cycle active for Ben Taylor.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--8-2',
    guide: 'Employee',
    ref: '8.2',
    title: 'Self-Assessment',
    purpose: 'Submit employee side of review.',
    outcome: 'Submitted; sign after manager if asked.',
    stepsText: 'Open active review | Answer questions | Submit | Sign if required',
    formData: 'Required answers',
    testData: 'EXISTING: Complete self-assessment questions → Submit → Sign if prompted.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--8-3',
    guide: 'Employee',
    ref: '8.3',
    title: 'Completed Reviews',
    purpose: 'Read outcomes.',
    outcome: 'Report view.',
    stepsText: 'Open completed review | Report',
    formData: 'N/A',
    testData: 'EXISTING: Completed review → Report.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--8-4',
    guide: 'Employee',
    ref: '8.4',
    title: '360 Feedback',
    purpose: 'Help peer review.',
    outcome: 'Submitted feedback.',
    stepsText: 'Open request | Answer | Submit',
    formData: 'Template answers',
    testData: 'EXISTING: 360 feedback form if assigned.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--9-1',
    guide: 'Employee',
    ref: '9.1',
    title: 'When to Raise a Ticket',
    purpose: 'Guidance on using helpdesk.',
    outcome: 'N/A informational.',
    stepsText: 'Read guide scenarios (pay, IT, policies, etc.)',
    formData: 'N/A',
    testData: 'EXISTING: Informational — when to raise ticket.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: 'employee-tickets',
  },
  {
    entryId: 'employee--9-2',
    guide: 'Employee',
    ref: '9.2',
    title: 'Creating Ticket',
    purpose: 'Request support.',
    outcome: 'Ticket created.',
    stepsText: 'Raise a Ticket | Raise a Ticket button | Modal Raise a Ticket | Create',
    formData: 'Same as Manager 7.1 (Subject, Category, Priority, Route to Team, Description; Create)',
    testData: 'NEW: Raise a Ticket | Subject [ManualTest] Employee recording | Category IT Support | Priority Low | Route to Team optional | Description Need VPN help for recording | Create.',
    notes: 'UI verified me/tickets/page.tsx',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: 'employee-tickets',
  },
  {
    entryId: 'employee--9-3',
    guide: 'Employee',
    ref: '9.3',
    title: 'Tracking Tickets',
    purpose: 'Monitor status.',
    outcome: 'Thread view.',
    stepsText: 'Raise a Ticket | List | Open ticket',
    formData: 'N/A',
    testData: 'EXISTING: List shows Open/In Progress/Resolved/Closed — open ticket from 9.2.',
    notes: 'Statuses in guide: Open, In Progress, Resolved, Closed',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: 'employee-tickets',
  },
  {
    entryId: 'employee--9-4',
    guide: 'Employee',
    ref: '9.4',
    title: 'Replying to Ticket',
    purpose: 'Add information.',
    outcome: 'Thread updated.',
    stepsText: 'Open ticket | Type reply | Send',
    formData: 'Message body',
    testData: 'EXISTING: Reply Additional info for recording test | Send.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: 'employee-tickets',
  },
  {
    entryId: 'employee--10-1',
    guide: 'Employee',
    ref: '10.1',
    title: 'Browsing Knowledge Centre',
    purpose: 'Find articles.',
    outcome: 'List/search results.',
    stepsText: 'Knowledge Centre | Category/search',
    formData: 'Search',
    testData: 'EXISTING: Knowledge Centre — search GDPR or policy.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--10-2',
    guide: 'Employee',
    ref: '10.2',
    title: 'Reading Article',
    purpose: 'Consume content.',
    outcome: 'Full article.',
    stepsText: 'Click article title',
    formData: 'N/A',
    testData: 'EXISTING: Open published article from enrich seed.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--11-1',
    guide: 'Employee',
    ref: '11.1',
    title: 'Onboarding Tasks',
    purpose: 'Complete induction.',
    outcome: 'Checklist progress.',
    stepsText: 'Onboarding if in sidebar OR Tasks',
    formData: 'N/A',
    testData: 'EXISTING: Onboarding in sidebar or Tasks — checklist from seed for new starters.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--11-2',
    guide: 'Employee',
    ref: '11.2',
    title: 'Completing Onboarding Items',
    purpose: 'Close starter tasks.',
    outcome: 'Items completed.',
    stepsText: 'Open each task | Follow instructions | Mark Completed',
    formData: 'Per task',
    testData: 'EXISTING: Complete onboarding task → mark Completed.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--12-1',
    guide: 'Employee',
    ref: '12.1',
    title: 'Account Settings',
    purpose: 'Personal prefs.',
    outcome: 'Saved.',
    stepsText: 'Settings',
    formData: 'Profile details; birthday visibility; notifications',
    testData: 'EXISTING: Settings — notifications / birthday visibility.',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'employee--12-2',
    guide: 'Employee',
    ref: '12.2',
    title: 'Changing Password',
    purpose: 'Rotate credentials.',
    outcome: 'New password.',
    stepsText: 'Log out | Forgot password? | Email flow',
    formData: 'Email; new password',
    testData: 'EXISTING: Log out → Forgot password flow with ben.taylor email (test only).',
    notes: 'Source: 03-employee-guide.md',
    role: 'employee',
    route: '/?org=platform-demo',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'partner-admin--1-1',
    guide: 'Partner Admin',
    ref: '1.1',
    title: 'Logging In',
    purpose: 'Open partner admin console.',
    outcome: 'Redirect to Admin Console /admin-console.',
    stepsText: 'http://localhost:3001 | Email | Password | Sign in',
    formData: 'e.g. partner.admin@meridian-hr.com; Demo123!',
    testData: 'EXISTING: http://localhost:3001 (or prod partner URL) | partner.admin@meridian-hr.com | Demo123!',
    notes: 'Source: 04-partner-admin-guide.md',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: true,
    setupKey: null,
  },
  {
    entryId: 'partner-admin--1-2',
    guide: 'Partner Admin',
    ref: '1.2',
    title: 'Admin Console Navigation',
    purpose: 'Reach console areas.',
    outcome: 'Correct section.',
    stepsText: 'Sidebar: Dashboard, Customer Tenants, Partnerships, Escalated Tickets',
    formData: 'N/A',
    testData: 'EXISTING: Admin Console sidebar — Dashboard, Customer Tenants, Partnerships, Escalated Tickets.',
    notes: 'Source: 04-partner-admin-guide.md',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'partner-admin--1-3',
    guide: 'Partner Admin',
    ref: '1.3',
    title: 'Switching to Organisation',
    purpose: 'Work inside tenant as admin.',
    outcome: 'Org admin dashboard for customer.',
    stepsText: 'Tenant detail | Login to Organisation | Use features | Admin Console link to return',
    formData: 'N/A',
    testData: 'EXISTING: Tenant platform-demo detail | Login to Organisation (if Tenant Assignment present).',
    notes: 'Requires Tenant Assignment per guide',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'partner-admin--1-4',
    guide: 'Partner Admin',
    ref: '1.4',
    title: 'Console Switching',
    purpose: 'Move between consoles if multiple roles.',
    outcome: 'Context switch.',
    stepsText: 'Footer/sidebar: Admin Console; Super Admin if allowed; Organisation Admin if linked',
    formData: 'N/A',
    testData: 'EXISTING: Console switcher links as role permits.',
    notes: 'Source: 04-partner-admin-guide.md',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'partner-admin--2-1',
    guide: 'Partner Admin',
    ref: '2.1',
    title: 'Dashboard Overview',
    purpose: 'Tenant portfolio metrics.',
    outcome: 'Stats and tenant table.',
    stepsText: 'Dashboard',
    formData: 'N/A',
    testData: 'EXISTING: Dashboard — tenant Platform Demo slug platform-demo user count from seed.',
    notes: 'Source: 04-partner-admin-guide.md',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'partner-admin--2-2',
    guide: 'Partner Admin',
    ref: '2.2',
    title: 'Creating New Tenant',
    purpose: 'Onboard customer org.',
    outcome: 'Tenant detail page for new org.',
    stepsText: 'New Tenant | Fill | Create Tenant',
    formData: 'Organisation name; Slug; Partner managed checkbox; Billing: email, contact name, address, city, state, postal code, country, VAT; Plan: Starter, Professional, Enterprise',
    testData: 'NEW: New Tenant | Organisation name ManualTest Org UNIQUE | Slug manualtest-unique-UNIQUE | Partner managed checked | Billing email billing.UNIQUE@example.com | Contact Recording Bot | Address line 1 Test Street 1 | City London | Postal SW1A 1AA | Country United Kingdom | VAT GB999999999 | Plan Professional | Create Tenant.',
    notes: 'Button Create Tenant on admin-console/tenants/new per codebase',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'partner-admin--2-3',
    guide: 'Partner Admin',
    ref: '2.3',
    title: 'Viewing Tenant Details',
    purpose: 'Inspect tenant.',
    outcome: 'Header, billing, admins visible.',
    stepsText: 'Click tenant row',
    formData: 'N/A',
    testData: 'EXISTING: Click tenant Platform Demo row OR tenant from 2.2.',
    notes: 'Source: 04-partner-admin-guide.md',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'partner-admin--2-4',
    guide: 'Partner Admin',
    ref: '2.4',
    title: 'Updating Billing',
    purpose: 'Keep billing master correct.',
    outcome: 'Saved billing.',
    stepsText: 'Tenant detail | Billing Details | Edit | Save Billing',
    formData: 'Billing fields in section',
    testData: 'EXISTING: Tenant from 2.2 → Billing Details → change City to Testville | Save Billing.',
    notes: 'Button Save Billing verified tenants/[id]/page.tsx',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'partner-admin--2-5',
    guide: 'Partner Admin',
    ref: '2.5',
    title: 'Adding Admin to Tenant',
    purpose: 'Invite org or partner admin.',
    outcome: 'User created/linked; invite sent.',
    stepsText: 'Tenant detail | Admins | Add Admin | Create & Invite',
    formData: 'Role: Organisation Admin or Partner Admin; First name; Last name; Email',
    testData: 'NEW on disposable tenant: Add Admin | Organisation Admin | First ManualTest | Last AdminInvite | Email manualtest.tenantadmin.UNIQUE@example.com | Create & Invite.',
    notes: 'Source: 04-partner-admin-guide.md',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'partner-admin--2-6',
    guide: 'Partner Admin',
    ref: '2.6',
    title: 'Login to Customer Organisation',
    purpose: 'Full org admin in tenant.',
    outcome: 'Switched session.',
    stepsText: 'Tenant detail | Login to Organisation',
    formData: 'N/A',
    testData: 'EXISTING: platform-demo tenant | Login to Organisation with assignment.',
    notes: 'Requires assignment per guide',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: null,
  },
  {
    entryId: 'partner-admin--3-1',
    guide: 'Partner Admin',
    ref: '3.1',
    title: 'Escalated Inbox',
    purpose: 'Work partner-level tickets.',
    outcome: 'Queue visible.',
    stepsText: 'Escalated Tickets',
    formData: 'N/A',
    testData: 'EXISTING: Escalated Tickets — ticket [Demo] SSO configuration for new client portal if HR doc setup run OR any PARTNER escalation.',
    notes: 'Source: 04-partner-admin-guide.md',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: 'partner-admin-tickets',
  },
  {
    entryId: 'partner-admin--3-2',
    guide: 'Partner Admin',
    ref: '3.2',
    title: 'Filtering Tickets',
    purpose: 'Find cases.',
    outcome: 'Filtered list.',
    stepsText: 'Search bar | Status Open, In Progress, Resolved, Closed | Priority Low, Medium, High, Urgent',
    formData: 'Search text; filters',
    testData: 'EXISTING: Search SSO or access | Status Open | Priority High.',
    notes: 'Source: 04-partner-admin-guide.md',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: 'partner-admin-tickets',
  },
  {
    entryId: 'partner-admin--3-3',
    guide: 'Partner Admin',
    ref: '3.3',
    title: 'Responding to Ticket',
    purpose: 'Reply or internal note.',
    outcome: 'Message posted.',
    stepsText: 'Open ticket | Type reply | Public reply OR Internal note | Send',
    formData: 'Message body; visibility mode',
    testData: 'EXISTING: Open escalated ticket | Public reply Partner recording test complete | Send.',
    notes: 'Source: 04-partner-admin-guide.md',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: 'partner-admin-tickets',
  },
  {
    entryId: 'partner-admin--3-4',
    guide: 'Partner Admin',
    ref: '3.4',
    title: 'Status and Priority',
    purpose: 'Reflect handling.',
    outcome: 'Updated ticket.',
    stepsText: 'Status dropdown | Priority dropdown',
    formData: 'Status; priority',
    testData: 'EXISTING: Status In Progress | Priority Medium dropdowns.',
    notes: 'Source: 04-partner-admin-guide.md',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: 'partner-admin-tickets',
  },
  {
    entryId: 'partner-admin--3-5',
    guide: 'Partner Admin',
    ref: '3.5',
    title: 'Escalate to Platform',
    purpose: 'Hand to platform support.',
    outcome: 'Escalated per guide.',
    stepsText: 'Open ticket | Escalate to Platform',
    formData: 'Confirm if UI prompts',
    testData: 'EXISTING: Escalate to Platform — only if UI shown and policy allows (sandbox).',
    notes: 'Source: 04-partner-admin-guide.md',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: 'partner-admin-tickets',
  },
  {
    entryId: 'partner-admin--3-6',
    guide: 'Partner Admin',
    ref: '3.6',
    title: 'De-escalating Ticket',
    purpose: 'Return to lower tier.',
    outcome: 'Ticket at partner or org level.',
    stepsText: 'Return to Partner OR Return to Org Admin (per options shown)',
    formData: 'N/A',
    testData: 'EXISTING: Return to Org Admin or Return to Partner per ticket state.',
    notes: 'Source: 04-partner-admin-guide.md',
    role: 'partner-admin',
    route: '/',
    skipPreLogin: false,
    setupKey: 'partner-admin-tickets',
  },
];

export const HR_SCENARIO_ENTRY_IDS: string[] = HR_SCENARIO_ROWS.map((r) => r.entryId);
